parameters:
#    acme_stamp.example.class: Acme\StampBundle\Example

services:
#    acme_stamp.example:
#        class: %acme_stamp.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
