<?php

namespace Acme\StampBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TestController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Acme\StampBundle\Controller\TestController();
        return $instance;
    }
}
